// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

const schemaPath = "prisma/schema.prisma";

export default {
  schema: schemaPath,
  migrations: {
    path: "prisma/migrations",
    seed: "npx ts-node --esm prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
};
